console.log("Hello /hOLA!")
console.log("Привет, как ты!")
console.log("Привет")
console.log("bonjour")
console.log("salut")
console.log("сегодня вторник")
console.log("hola me llamo gabriel")
console.log("меня зовут Габриэль")
console.log("today is tuesday")
console.log("hello how are you")
